#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"

COMMIT_HASH=$(GIT_DIR=$DOKKU_ROOT/$APP git rev-parse --short HEAD)

id=$(echo "export COMMIT_HASH=$COMMIT_HASH" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.profile.d/git_rev.sh")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
